export type CosmeticCategory = "hat" | "decoration";
export type CrateRarity = "common" | "uncommon" | "rare" | "ultra-rare" | "legendary";

export type EmojiType = "emoji" | "image";

export interface CosmeticDefinition {
  id: string;
  name: string;
  description: string;
  category: CosmeticCategory;
  emoji?: string; // Emoji character or URL to png/gif
  url?: string; // Emoji character or URL to png/gif
  cost: number;
  rarity: CrateRarity;
}

export const RARITY_VALUE: Record<CrateRarity, number> = {
  common: 0, // 10-50
  uncommon: 1, // 100-500
  rare: 2, // 500-1000
  "ultra-rare": 3, // 1000-5000
  legendary: 4 // 5000-10000
};

export const RARITY_CONFIG: Record<CrateRarity, { label: string; color: string; glowColor: string; bgColor: string }> = {
  common: {
    label: "Common",
    color: "#9ca3af",
    glowColor: "rgba(156,163,175,0.75)",
    bgColor: "rgba(55,65,81,0.9)",
  },
  uncommon: {
    label: "Uncommon",
    color: "#22c55e",
    glowColor: "rgba(34,197,94,0.75)",
    bgColor: "rgba(20,83,45,0.9)",
  },
  rare: {
    label: "Rare",
    color: "#3b82f6",
    glowColor: "rgba(59,130,246,0.75)",
    bgColor: "rgba(30,58,138,0.9)",
  },
  "ultra-rare": {
    label: "Ultra Rare",
    color: "#a855f7",
    glowColor: "rgba(168,85,247,0.75)",
    bgColor: "rgba(88,28,135,0.9)",
  },
  legendary: {
    label: "LEGENDARY",
    color: "#f59e0b",
    glowColor: "rgba(245,158,11,0.9)",
    bgColor: "rgba(120,53,15,0.9)",
  },
};

export const COSMETICS: CosmeticDefinition[] = [
  // --- Hats ---
  {
    id: "hat_cowboy",
    name: "Cowboy Hat",
    description: "Feel the Texan spirit :p",
    category: "hat",
    emoji: "🤠",
    cost: 750,
    rarity: "rare",
  },
  {
    id: "hat_graduation",
    name: "Graduation Cap",
    description: "Don't worry, you'll get this someday.",
    category: "hat",
    emoji: "🎓",
    cost: 400,
    rarity: "uncommon",
  },
  {
    id: "hat_crown",
    name: "Crown",
    description: "MY GLORIOUS QUEEN (OR KING)",
    category: "hat",
    emoji: "👑",
    cost: 10000,
    rarity: "legendary",
  },
  {
    id: "hat_party",
    name: "Party Hat",
    description: "Celebrateeee",
    category: "hat",
    emoji: "🎉",
    cost: 100,
    rarity: "uncommon",
  },
  {
    id: "hat_top",
    name: "Top Hat",
    description: "Haur Haur Haur Haur Haur",
    category: "hat",
    emoji: "🎩",
    cost: 0,
    rarity: "ultra-rare",
  },
  {
    id: "hat_santa",
    name: "Santa Hat",
    description: "Feeling quite jolly today, eh?",
    category: "hat",
    emoji: "🎅",
    cost: 500,
    rarity: "rare",
  },
  {
    id: "hat_suprise",
    name: "Exclamation!!",
    description: "WHAT!!11!1!!!1",
    category: "hat",
    emoji: "‼",
    cost: 650,
    rarity: "rare",
  },
  {
    id: "hat_suprised_question",
    name: "Exclamation!?",
    description: "WHAT!?!?!???",
    category: "hat",
    emoji: "⁉",
    cost: 8000,
    rarity: "legendary",
  },
  {
    id: "hat_question",
    name: "Huh?",
    description: "huh?",
    category: "hat",
    emoji: "❓",
    cost: 150,
    rarity: "uncommon",
  },
  {
    id: "hat_stephen",
    name: "Stephen",
    description: "(the rat, not the person)",
    category: "hat",
    emoji: "🐀",
    cost: 0,
    rarity: "ultra-rare",
  },
  {
    id: "hat_plant",
    name: "Sproutling",
    description: "Maybe one day you'll grow a flower",
    category: "hat",
    emoji: "🌱",
    cost: 40,
    rarity: "common",
  },
  {
    id: "hat_rain",
    name: "Rain Cloud",
    description: "A little wet",
    category: "hat",
    emoji: "🌧",
    cost: 300,
    rarity: "uncommon",
  },
  {
    id: "hat_bow",
    name: "Pink Bow",
    description: "Very cute",
    category: "hat",
    emoji: "🎀",
    cost: 30,
    rarity: "common",
  },
  {
    id: "hat_teddy",
    name: "Teddy Bear",
    description: "Mr. Roosevelt himself",
    category: "hat",
    emoji: "🧸",
    cost: 850,
    rarity: "rare",
  },
  {
    id: "hat_cap",
    name: "Baseball Cap",
    description: "Your standard billed cap",
    category: "hat",
    emoji: "🧢",
    cost: 50,
    rarity: "common",
  },
  {
    id: "hat_books",
    name: "Books",
    description: "For those that like wearing books on their head",
    category: "hat",
    emoji: "📚",
    cost: 600,
    rarity: "rare",
  },
  {
    id: "hat_bubbles",
    name: "Bubbles",
    description: "How clean",
    category: "hat",
    emoji: "🫧",
    cost: 2000,
    rarity: "ultra-rare",
  },
  // --- Cosmetics ---
  {
    id: "decoration_cherry",
    name: "Cherry Blossom",
    description: "Wowwww so pretty",
    category: "decoration",
    emoji: "🌸",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_sunflower",
    name: "Sunflower",
    description: "Wowwww so sunny",
    category: "decoration",
    emoji: "🌻",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_cactus",
    name: "Cactus",
    description: "Wowwww so prickly",
    category: "decoration",
    emoji: "🌵",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_potted",
    name: "Potted Plant",
    description: "Wowwww so... potted?",
    category: "decoration",
    emoji: "🪴",
    cost: 40,
    rarity: "common",
  },
  {
    id: "decoration_mushroom",
    name: "Mushroom",
    description: "Wowwww so poisonous",
    category: "decoration",
    emoji: "🍄",
    cost: 200,
    rarity: "uncommon",
  },
  {
    id: "decoration_four_leaf",
    name: "Four Leaf Clover",
    description: "Wowwww so lucky",
    category: "decoration",
    emoji: "🍀",
    cost: 500,
    rarity: "rare",
  },
  {
    id: "decoration_six_seven",
    name: "6 7",
    description: "If gambling got you here, congratulations. You have our recognition.",
    category: "decoration",
    emoji: "6️⃣7️⃣",
    cost: 0,
    rarity: "legendary",
  },
  {
    id: "decoration_rainbow",
    name: "Rainbow",
    description: "Double rainbow all the way across the sky.",
    category: "decoration",
    emoji: "🌈",
    cost: 250,
    rarity: "uncommon",
  },
  {
    id: "decoration_fire",
    name: "Fire",
    description: "You're on fire! (hopefully not literally)",
    category: "decoration",
    emoji: "🔥",
    cost: 500,
    rarity: "uncommon",
  },
  {
    id: "decoration_snowflake",
    name: "Snowflake",
    description: "Each one is unique, just like you.",
    category: "decoration",
    emoji: "❄️",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_lightning",
    name: "Lightning Bolt",
    description: "Shockingly good taste.",
    category: "decoration",
    emoji: "⚡",
    cost: 400,
    rarity: "uncommon",
  },
  {
    id: "decoration_star",
    name: "Shooting Star",
    description: "Make a wish.",
    category: "decoration",
    emoji: "🌠",
    cost: 750,
    rarity: "rare",
  },
  {
    id: "decoration_comet",
    name: "Comet",
    description: "Once in a lifetime. Like your scouting accuracy.",
    category: "decoration",
    emoji: "☄️",
    cost: 1000,
    rarity: "rare",
  },
  {
    id: "decoration_gem",
    name: "Gem",
    description: "Rare find.",
    category: "decoration",
    emoji: "💎",
    cost: 2000,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_trophy",
    name: "Trophy",
    description: "For those who deserve recognition.",
    category: "decoration",
    emoji: "🏆",
    cost: 0,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_robot",
    name: "Robot",
    description: "Beep boop. FRC approved.",
    category: "decoration",
    emoji: "🤖",
    cost: 600,
    rarity: "rare",
  },
  {
    id: "decoration_wrench",
    name: "Wrench",
    description: "In case the robot breaks. Again.",
    category: "decoration",
    emoji: "🔧",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_gear",
    name: "Gear",
    description: "The real MVP of every robot.",
    category: "decoration",
    emoji: "⚙️",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_magnet",
    name: "Magnet",
    description: "Attracting W's since day one.",
    category: "decoration",
    emoji: "🧲",
    cost: 150,
    rarity: "uncommon",
  },
  {
    id: "decoration_satellite",
    name: "Satellite",
    description: "Always watching. Always scouting.",
    category: "decoration",
    emoji: "🛰️",
    cost: 800,
    rarity: "rare",
  },
  {
    id: "decoration_alien",
    name: "Alien",
    description: "Your scouting skills are out of this world.",
    category: "decoration",
    emoji: "👽",
    cost: 200,
    rarity: "uncommon",
  },
  {
    id: "decoration_ghost",
    name: "Ghost",
    description: "Invisible on defense, visible in the data.",
    category: "decoration",
    emoji: "👻",
    cost: 100,
    rarity: "uncommon",
  },
  {
    id: "decoration_dragon",
    name: "Dragon",
    description: "Breathe fire on the competition.",
    category: "decoration",
    emoji: "🐉",
    cost: 1500,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_shark",
    name: "Shark",
    description: "Always moving forward.",
    category: "decoration",
    emoji: "🦈",
    cost: 1000,
    rarity: "rare",
  },
  {
    id: "decoration_eagle",
    name: "Eagle",
    description: "Eyes on the field at all times.",
    category: "decoration",
    emoji: "🦅",
    cost: 850,
    rarity: "rare",
  },
  {
    id: "decoration_penguin",
    name: "Penguin",
    description: "Cool under pressure.",
    category: "decoration",
    emoji: "🐧",
    cost: 150,
    rarity: "uncommon",
  },
  {
    id: "decoration_cat",
    name: "Cat",
    description: "Nine lives, infinite rematches.",
    category: "decoration",
    emoji: "🐱",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_fox",
    name: "Fox",
    description: "Sly and strategic.",
    category: "decoration",
    emoji: "🦊",
    cost: 100,
    rarity: "uncommon",
  },
  {
    id: "decoration_panda",
    name: "Panda",
    description: "Rare, precious, and surprisingly strong.",
    category: "decoration",
    emoji: "🐼",
    cost: 150,
    rarity: "uncommon",
  },
  {
    id: "decoration_pizza",
    name: "Pizza",
    description: "The official fuel of build season.",
    category: "decoration",
    emoji: "🍕",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_boba",
    name: "Bubble Tea",
    description: "For the late-night coding sessions.",
    category: "decoration",
    emoji: "🧋",
    cost: 700,
    rarity: "rare",
  },
  {
    id: "decoration_soda",
    name: "Soda",
    description: "Carbonated motivation.",
    category: "decoration",
    emoji: "🥤",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_moon",
    name: "Crescent Moon",
    description: "For those midnight calibration sessions.",
    category: "decoration",
    emoji: "🌙",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_sun",
    name: "Sun",
    description: "Bright ideas only.",
    category: "decoration",
    emoji: "☀️",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_volcano",
    name: "Volcano",
    description: "Big boom lmao.",
    category: "decoration",
    emoji: "🌋",
    cost: 750,
    rarity: "rare",
  },
  {
    id: "decoration_crystal_ball",
    name: "Crystal Ball",
    description: "Predicting match outcomes since 2026.",
    category: "decoration",
    emoji: "🔮",
    cost: 3000,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_dice",
    name: "Dice",
    description: "Sometimes alliances are just luck.",
    category: "decoration",
    emoji: "🎲",
    cost: 20,
    rarity: "uncommon",
  },
  {
    id: "decoration_joystick",
    name: "Joystick",
    description: "Please don't crash our robot",
    category: "decoration",
    emoji: "🕹️",
    cost: 900,
    rarity: "rare",
  },
  {
    id: "decoration_speak",
    name: "Yelling",
    description: "Bros just yapping",
    category: "decoration",
    emoji: "🗣",
    cost: 350,
    rarity: "uncommon",
  },
  {
    id: "decoration_you",
    name: "Pointing",
    description: "It's all your fault",
    category: "decoration",
    emoji: "🫵",
    cost: 30,
    rarity: "common",
  },
  {
    id: "decoration_eyes",
    name: "Eyes",
    description: "I can see you 👁️👁️",
    category: "decoration",
    emoji: "👀",
    cost: 400,
    rarity: "uncommon",
  },
  {
    id: "decoration_cursing",
    name: "Cursing",
    description: "Grrrrrr....",
    category: "decoration",
    emoji: "🤬",
    cost: 650,
    rarity: "rare",
  },
  {
    id: "decoration_cc_rain",
    name: "Happy Rain",
    description: "Rain approved",
    category: "decoration",
    url: "/shop/decoration_cc_rain.png",
    cost: 4000,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_aura_loss",
    name: "Aura Loss",
    description: "All I do is win no matter what",
    category: "decoration",
    url: "/shop/decoration_aura_loss.gif",
    cost: 0,
    rarity: "legendary",
  },
  {
    id: "decoration_rainbow_parrot",
    name: "PARROT",
    description: "A little excited to scout",
    category: "decoration",
    url: "/shop/decoration_rainbow_parrot.gif",
    cost: 8000,
    rarity: "legendary",
  },
  {
    id: "decoration_rainbow_dance",
    name: "Blob Dance",
    description: "Just a chill guy",
    category: "decoration",
    url: "/shop/decoration_rainbow_dance.gif",
    cost: 0,
    rarity: "legendary",
  },
];

// Dev guard: catch duplicate IDs
if (import.meta.env.DEV) {
  const ids = COSMETICS.map((c) => c.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length > 0) {
    console.error("[cosmetics.ts] Duplicate cosmetic IDs detected:", dupes);
  }
}
