export type CosmeticCategory = "hat" | "decoration";
export type CrateRarity = "common" | "uncommon" | "rare" | "ultra-rare" | "legendary";

export type EmojiType = "emoji" | "image";

export interface CosmeticDefinition {
  id: string;
  name: string;
  description: string;
  category: CosmeticCategory;
  emoji: string; // Emoji character or URL to png/gif
  emojiType?: EmojiType; // "emoji" for standard emoji, "image" for png/gif URL
  cost: number;
  rarity: CrateRarity;
}

export const RARITY_CONFIG: Record<CrateRarity, { label: string; color: string; glowColor: string; bgColor: string }> = {
  common: {
    label: "Common",
    color: "#9ca3af",
    glowColor: "rgba(156,163,175,0.75)",
    bgColor: "rgba(55,65,81,0.9)",
  },
  uncommon: {
    label: "Uncommon",
    color: "#22c55e",
    glowColor: "rgba(34,197,94,0.75)",
    bgColor: "rgba(20,83,45,0.9)",
  },
  rare: {
    label: "Rare",
    color: "#3b82f6",
    glowColor: "rgba(59,130,246,0.75)",
    bgColor: "rgba(30,58,138,0.9)",
  },
  "ultra-rare": {
    label: "Ultra Rare",
    color: "#a855f7",
    glowColor: "rgba(168,85,247,0.75)",
    bgColor: "rgba(88,28,135,0.9)",
  },
  legendary: {
    label: "LEGENDARY",
    color: "#f59e0b",
    glowColor: "rgba(245,158,11,0.9)",
    bgColor: "rgba(120,53,15,0.9)",
  },
};

export const COSMETICS: CosmeticDefinition[] = [
  // --- Hats ---
  {
    id: "hat_cowboy",
    name: "Cowboy Hat",
    description: "Feel the Texan spirit :p",
    category: "hat",
    emoji: "🤠",
    cost: 25,
    rarity: "rare",
  },
  {
    id: "hat_graduation",
    name: "Graduation Cap",
    description: "Don't worry, you'll get this someday.",
    category: "hat",
    emoji: "🎓",
    cost: 15,
    rarity: "common",
  },
  {
    id: "hat_crown",
    name: "Crown",
    description: "MY GLORIOUS QUEEN (OR KING)",
    category: "hat",
    emoji: "👑",
    cost: 100,
    rarity: "legendary",
  },
  {
    id: "hat_party",
    name: "Party Hat",
    description: "Celebrateeee",
    category: "hat",
    emoji: "🎉",
    cost: 30,
    rarity: "uncommon",
  },
  {
    id: "hat_top",
    name: "Top Hat",
    description: "Haur Haur Haur Haur Haur",
    category: "hat",
    emoji: "🎩",
    cost: 50,
    rarity: "ultra-rare",
  },
  {
    id: "hat_santa",
    name: "Santa Hat",
    description: "Feeling quite jolly today, eh?",
    category: "hat",
    emoji: "🎅",
    cost: 40,
    rarity: "rare",
  },
  // --- Cosmetics ---
  {
    id: "decoration_cherry",
    name: "Cherry Blossom",
    description: "Wowwww so pretty",
    category: "decoration",
    emoji: "🌸",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_sunflower",
    name: "Sunflower",
    description: "Wowwww so sunny",
    category: "decoration",
    emoji: "🌻",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_cactus",
    name: "Cactus",
    description: "Wowwww so prickly",
    category: "decoration",
    emoji: "🌵",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_potted",
    name: "Potted Plant",
    description: "Wowwww so... potted?",
    category: "decoration",
    emoji: "🪴",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_mushroom",
    name: "Mushroom",
    description: "Wowwww so poisonous",
    category: "decoration",
    emoji: "🍄",
    cost: 25,
    rarity: "uncommon",
  },
  {
    id: "decoration_four_leaf",
    name: "Four Leaf Clover",
    description: "Wowwww so lucky",
    category: "decoration",
    emoji: "🍀",
    cost: 35,
    rarity: "rare",
  },
  {
    id: "decoration_six_seven",
    name: "6 7",
    description: "If gambling got you here, congratulations. You have our recognition.",
    category: "decoration",
    emoji: "6️⃣7️⃣",
    cost: 1000000,
    rarity: "legendary",
  },
  {
    id: "decoration_rainbow",
    name: "Rainbow",
    description: "Double rainbow all the way across the sky.",
    category: "decoration",
    emoji: "🌈",
    cost: 30,
    rarity: "uncommon",
  },
  {
    id: "decoration_fire",
    name: "Fire",
    description: "You're on fire! (hopefully not literally)",
    category: "decoration",
    emoji: "🔥",
    cost: 20,
    rarity: "uncommon",
  },
  {
    id: "decoration_snowflake",
    name: "Snowflake",
    description: "Each one is unique, just like you.",
    category: "decoration",
    emoji: "❄️",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_lightning",
    name: "Lightning Bolt",
    description: "Shockingly good taste.",
    category: "decoration",
    emoji: "⚡",
    cost: 25,
    rarity: "uncommon",
  },
  {
    id: "decoration_star",
    name: "Shooting Star",
    description: "Make a wish.",
    category: "decoration",
    emoji: "🌠",
    cost: 40,
    rarity: "rare",
  },
  {
    id: "decoration_comet",
    name: "Comet",
    description: "Once in a lifetime. Like your scouting accuracy.",
    category: "decoration",
    emoji: "☄️",
    cost: 45,
    rarity: "rare",
  },
  {
    id: "decoration_gem",
    name: "Gem",
    description: "Rare find.",
    category: "decoration",
    emoji: "💎",
    cost: 75,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_trophy",
    name: "Trophy",
    description: "For those who deserve recognition.",
    category: "decoration",
    emoji: "🏆",
    cost: 60,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_robot",
    name: "Robot",
    description: "Beep boop. FRC approved.",
    category: "decoration",
    emoji: "🤖",
    cost: 35,
    rarity: "rare",
  },
  {
    id: "decoration_wrench",
    name: "Wrench",
    description: "In case the robot breaks. Again.",
    category: "decoration",
    emoji: "🔧",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_gear",
    name: "Gear",
    description: "The real MVP of every robot.",
    category: "decoration",
    emoji: "⚙️",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_magnet",
    name: "Magnet",
    description: "Attracting W's since day one.",
    category: "decoration",
    emoji: "🧲",
    cost: 25,
    rarity: "uncommon",
  },
  {
    id: "decoration_satellite",
    name: "Satellite",
    description: "Always watching. Always scouting.",
    category: "decoration",
    emoji: "🛰️",
    cost: 50,
    rarity: "rare",
  },
  {
    id: "decoration_alien",
    name: "Alien",
    description: "Your scouting skills are out of this world.",
    category: "decoration",
    emoji: "👽",
    cost: 30,
    rarity: "uncommon",
  },
  {
    id: "decoration_ghost",
    name: "Ghost",
    description: "Invisible on defense, visible in the data.",
    category: "decoration",
    emoji: "👻",
    cost: 25,
    rarity: "uncommon",
  },
  {
    id: "decoration_dragon",
    name: "Dragon",
    description: "Breathe fire on the competition.",
    category: "decoration",
    emoji: "🐉",
    cost: 80,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_shark",
    name: "Shark",
    description: "Always moving forward.",
    category: "decoration",
    emoji: "🦈",
    cost: 40,
    rarity: "rare",
  },
  {
    id: "decoration_eagle",
    name: "Eagle",
    description: "Eyes on the field at all times.",
    category: "decoration",
    emoji: "🦅",
    cost: 35,
    rarity: "rare",
  },
  {
    id: "decoration_penguin",
    name: "Penguin",
    description: "Cool under pressure.",
    category: "decoration",
    emoji: "🐧",
    cost: 20,
    rarity: "uncommon",
  },
  {
    id: "decoration_cat",
    name: "Cat",
    description: "Nine lives, infinite rematches.",
    category: "decoration",
    emoji: "🐱",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_fox",
    name: "Fox",
    description: "Sly and strategic.",
    category: "decoration",
    emoji: "🦊",
    cost: 25,
    rarity: "uncommon",
  },
  {
    id: "decoration_panda",
    name: "Panda",
    description: "Rare, precious, and surprisingly strong.",
    category: "decoration",
    emoji: "🐼",
    cost: 30,
    rarity: "uncommon",
  },
  {
    id: "decoration_pizza",
    name: "Pizza",
    description: "The official fuel of build season.",
    category: "decoration",
    emoji: "🍕",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_boba",
    name: "Bubble Tea",
    description: "For the late-night coding sessions.",
    category: "decoration",
    emoji: "🧋",
    cost: 15,
    rarity: "common",
  },
  {
    id: "decoration_soda",
    name: "Soda",
    description: "Carbonated motivation.",
    category: "decoration",
    emoji: "🥤",
    cost: 10,
    rarity: "common",
  },
  {
    id: "decoration_moon",
    name: "Crescent Moon",
    description: "For those midnight calibration sessions.",
    category: "decoration",
    emoji: "🌙",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_sun",
    name: "Sun",
    description: "Bright ideas only.",
    category: "decoration",
    emoji: "☀️",
    cost: 20,
    rarity: "common",
  },
  {
    id: "decoration_volcano",
    name: "Volcano",
    description: "When the match timer hits zero.",
    category: "decoration",
    emoji: "🌋",
    cost: 35,
    rarity: "rare",
  },
  {
    id: "decoration_crystal_ball",
    name: "Crystal Ball",
    description: "Predicting match outcomes since 2026.",
    category: "decoration",
    emoji: "🔮",
    cost: 55,
    rarity: "ultra-rare",
  },
  {
    id: "decoration_dice",
    name: "Dice",
    description: "Sometimes alliances are just luck.",
    category: "decoration",
    emoji: "🎲",
    cost: 20,
    rarity: "uncommon",
  },
  {
    id: "decoration_joystick",
    name: "Joystick",
    description: "Drivers only.",
    category: "decoration",
    emoji: "🕹️",
    cost: 30,
    rarity: "rare",
  },
];

// Dev guard: catch duplicate IDs
if (import.meta.env.DEV) {
  const ids = COSMETICS.map((c) => c.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length > 0) {
    console.error("[cosmetics.ts] Duplicate cosmetic IDs detected:", dupes);
  }
}
