"""Build src/config/frcdleRarity.ts from the FRCdle season snapshot (build_snapshot.py).

Scores all 1,000,000 six-digit FRCdle rolls the same way FrcdleGame does
(every 2-5 digit window without a leading zero, a team counted once per
appearance, teams missing from the snapshot count 0) and writes a CDF table:
for each xP breakpoint, the percent of rolls that score strictly less.

Usage: python3 -I scripts/frcdle-rarity/generate_table.py src/config/frcdleSnapshot2026.json src/config/frcdleRarity.ts
"""
import bisect, json, sys

snapshot_path, out_path = sys.argv[1], sys.argv[2]
snapshot = json.load(open(snapshot_path))
xp = {team: team_xp for team, _, team_xp in snapshot["teams"]}

totals = []
best = (float("-inf"), "", [])
for n in range(1_000_000):
    digits = f"{n:06d}"
    seen = []
    for length in range(2, 6):
        for start in range(7 - length):
            window = digits[start:start + length]
            if window[0] != "0":
                team = int(window)
                if team in xp:
                    seen.append(team)
    total = round(sum(xp[team] for team in seen), 2)
    totals.append(total)
    if total > best[0]:
        best = (total, digits, sorted(seen))
totals.sort()
count = len(totals)

# Breakpoints every 0.1% of rolls, every 0.01% in the top 1%, plus the max.
fractions = [i / 1000 for i in range(990)] + [0.99 + i / 10000 for i in range(100)]
values = sorted({totals[min(count - 1, int(f * count))] for f in fractions} | {totals[-1]})
cdf = [(v, round(100 * bisect.bisect_left(totals, v) / count, 4)) for v in values]

with open(out_path, "w") as out:
    out.write("// Generated by scripts/frcdle-rarity/generate_table.py — do not edit by hand.\n")
    out.write(f"// Source: snapshot of {len(xp)} on-season teams captured {snapshot['capturedAt']}, scored over all {count:,} rolls.\n\n")
    out.write(f"export const FRCDLE_XP_TABLE_MAX = {best[0]};\n")
    out.write(f"export const FRCDLE_XP_TABLE_MAX_ROLL = {json.dumps(best[1])}; // teams {best[2]}\n\n")
    out.write("/** [combined xP, percent of all rolls scoring strictly less], ascending by xP. */\n")
    out.write("export const FRCDLE_XP_CDF: ReadonlyArray<readonly [number, number]> = [\n")
    for v, p in cdf:
        out.write(f"  [{v}, {p}],\n")
    out.write("];\n")

print(f"{len(xp)} rated teams; max {best[0]} on roll {best[1]} {best[2]}; {len(cdf)} breakpoints")
print("median", totals[count // 2], "p90", totals[int(count * 0.9)], "p99", totals[int(count * 0.99)])
print("rolls above 871:", count - bisect.bisect_right(totals, 871))
